name: Todo app CI/CD

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.acton != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create env file
        run: |
          touch .env.${{ secrets.REACT_APP_ENV }}          
          echo REACT_APP_ENV=${{ secrets.REACT_APP_ENV }} >> .env
          echo REACT_APP_TENANT_ID=${{ secrets.REACT_APP_TENANT_ID }} >> .env
          echo REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }} >> .env
          echo REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }} >> .env
          echo REACT_APP_STORAGE_ACCOUNT_NAME=${{ secrets.REACT_APP_STORAGE_ACCOUNT_NAME }} >> .env

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_COAST_075e0ea00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
